version: '3.8'
services:
  milvus:
    image: milvusdb/milvus:v2.2.7
    container_name: milvus
    ports:
      - "19530:19530"
    environment:
      - MILVUS_ROOT_COORD="localhost"
    command: ["milvus", "run"]

  fastapi:
    build:
      context: .
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - milvus
    environment:
      - MILVUS_HOST=milvus
    networks:
      - milvus_network

networks:
  milvus_network:
    driver: bridge
